### ISSUE TITLE
Github Preview

### ISSUE THREAD

**Issue by Tereseus** [nerdrax/prj-rev-bwfs-dasmoto#1]
Github has a new preview feature that makes it easy to view a repository's HTML and CSS in action, it is something that is not enabled on your project and one thing you can do to solve that is to remove the extra level you have with the Dasmoto folder, you can just have the HTML and resource folder be the main part of the project. That will enable an easy preview option.

**Comment by nerdrax** [comment]
Oh, I am new to this Github environment, I will surely l try that next time. 
Thank you for the advise.

**Comment by Tereseus** [comment]
Ok great
