### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Tereseus** [nerdrax/prj-rev-bwfs-dasmoto#3]
Again great job on your HTML, you used divs correctly which is not something a lot of users do and your repo looks exactly like the solution. The only advice I can give you for the HTML section is to use more notes, especially in the future when you are working on bigger projects it will help a lot. Great job!

**Comment by nerdrax** [comment]
Dear @Tzuridis thank you. The notes you are referring to, are they comments? or another thing?

**Comment by Tereseus** [comment]
Yes comments
