### ISSUE TITLE
Summary - Exceeds Expecations

### ISSUE THREAD

**Issue by Tereseus** [nerdrax/prj-rev-bwfs-dasmoto#4]
You did a great job with this project, everything is correct. The only things you can change for this repo is the file structure so that github's preview option is available for your repo and to include notes in your HTML. Other than that a perfect job!

Keep up the good work!

**Comment by nerdrax** [comment]
Thank you for the review! I'm glad I did good, hehe. I will definitely try that preview option of github working next time.

**Comment by Tereseus** [comment]
Ok great
